version: '3.8'

services:
  db:
    image: postgres:15
    container_name: alfalux_db
    restart: always
    environment:
      POSTGRES_USER: user_alfalux
      POSTGRES_PASSWORD: password_alfalux
      POSTGRES_DB: alfalux_propostas
    ports:
      - "5432:5432"
    healthcheck:
      #Este comando verifica se o Postgres está pronto para aceitar conexões
      test: ["CMD-SHELL", "pg_isready -U user_alfalux -d alfalux_propostas"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: alfalux_api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy #Só inicia a app quando o db estiver 'healthy'
    environment:
      DATABASE_URL: postgresql://user_alfalux:password_alfalux@db:5432/alfalux_propostas

  pgadmin:
    image: dpage/pgadmin4
    container_name: alfalux_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data: