/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GeradorIndexRouteImport } from './routes/gerador.index'
import { Route as GeradorRevisaoRouteImport } from './routes/gerador.revisao'
import { Route as GeradorProdutosRouteImport } from './routes/gerador.produtos'
import { Route as GeradorNovaRouteImport } from './routes/gerador.nova'
import { Route as GeradorFixosRouteImport } from './routes/gerador.fixos'
import { Route as GeradorConsultarRouteImport } from './routes/gerador.consultar'
import { Route as GeradorConclusaoRouteImport } from './routes/gerador.conclusao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorIndexRoute = GeradorIndexRouteImport.update({
  id: '/gerador/',
  path: '/gerador/',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorRevisaoRoute = GeradorRevisaoRouteImport.update({
  id: '/gerador/revisao',
  path: '/gerador/revisao',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorProdutosRoute = GeradorProdutosRouteImport.update({
  id: '/gerador/produtos',
  path: '/gerador/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorNovaRoute = GeradorNovaRouteImport.update({
  id: '/gerador/nova',
  path: '/gerador/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorFixosRoute = GeradorFixosRouteImport.update({
  id: '/gerador/fixos',
  path: '/gerador/fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorConsultarRoute = GeradorConsultarRouteImport.update({
  id: '/gerador/consultar',
  path: '/gerador/consultar',
  getParentRoute: () => rootRouteImport,
} as any)
const GeradorConclusaoRoute = GeradorConclusaoRouteImport.update({
  id: '/gerador/conclusao',
  path: '/gerador/conclusao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gerador/conclusao': typeof GeradorConclusaoRoute
  '/gerador/consultar': typeof GeradorConsultarRoute
  '/gerador/fixos': typeof GeradorFixosRoute
  '/gerador/nova': typeof GeradorNovaRoute
  '/gerador/produtos': typeof GeradorProdutosRoute
  '/gerador/revisao': typeof GeradorRevisaoRoute
  '/gerador/': typeof GeradorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gerador/conclusao': typeof GeradorConclusaoRoute
  '/gerador/consultar': typeof GeradorConsultarRoute
  '/gerador/fixos': typeof GeradorFixosRoute
  '/gerador/nova': typeof GeradorNovaRoute
  '/gerador/produtos': typeof GeradorProdutosRoute
  '/gerador/revisao': typeof GeradorRevisaoRoute
  '/gerador': typeof GeradorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gerador/conclusao': typeof GeradorConclusaoRoute
  '/gerador/consultar': typeof GeradorConsultarRoute
  '/gerador/fixos': typeof GeradorFixosRoute
  '/gerador/nova': typeof GeradorNovaRoute
  '/gerador/produtos': typeof GeradorProdutosRoute
  '/gerador/revisao': typeof GeradorRevisaoRoute
  '/gerador/': typeof GeradorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gerador/conclusao'
    | '/gerador/consultar'
    | '/gerador/fixos'
    | '/gerador/nova'
    | '/gerador/produtos'
    | '/gerador/revisao'
    | '/gerador/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gerador/conclusao'
    | '/gerador/consultar'
    | '/gerador/fixos'
    | '/gerador/nova'
    | '/gerador/produtos'
    | '/gerador/revisao'
    | '/gerador'
  id:
    | '__root__'
    | '/'
    | '/gerador/conclusao'
    | '/gerador/consultar'
    | '/gerador/fixos'
    | '/gerador/nova'
    | '/gerador/produtos'
    | '/gerador/revisao'
    | '/gerador/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GeradorConclusaoRoute: typeof GeradorConclusaoRoute
  GeradorConsultarRoute: typeof GeradorConsultarRoute
  GeradorFixosRoute: typeof GeradorFixosRoute
  GeradorNovaRoute: typeof GeradorNovaRoute
  GeradorProdutosRoute: typeof GeradorProdutosRoute
  GeradorRevisaoRoute: typeof GeradorRevisaoRoute
  GeradorIndexRoute: typeof GeradorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador/': {
      id: '/gerador/'
      path: '/gerador'
      fullPath: '/gerador/'
      preLoaderRoute: typeof GeradorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador/revisao': {
      id: '/gerador/revisao'
      path: '/gerador/revisao'
      fullPath: '/gerador/revisao'
      preLoaderRoute: typeof GeradorRevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador/produtos': {
      id: '/gerador/produtos'
      path: '/gerador/produtos'
      fullPath: '/gerador/produtos'
      preLoaderRoute: typeof GeradorProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador/nova': {
      id: '/gerador/nova'
      path: '/gerador/nova'
      fullPath: '/gerador/nova'
      preLoaderRoute: typeof GeradorNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador/fixos': {
      id: '/gerador/fixos'
      path: '/gerador/fixos'
      fullPath: '/gerador/fixos'
      preLoaderRoute: typeof GeradorFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador/consultar': {
      id: '/gerador/consultar'
      path: '/gerador/consultar'
      fullPath: '/gerador/consultar'
      preLoaderRoute: typeof GeradorConsultarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gerador/conclusao': {
      id: '/gerador/conclusao'
      path: '/gerador/conclusao'
      fullPath: '/gerador/conclusao'
      preLoaderRoute: typeof GeradorConclusaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GeradorConclusaoRoute: GeradorConclusaoRoute,
  GeradorConsultarRoute: GeradorConsultarRoute,
  GeradorFixosRoute: GeradorFixosRoute,
  GeradorNovaRoute: GeradorNovaRoute,
  GeradorProdutosRoute: GeradorProdutosRoute,
  GeradorRevisaoRoute: GeradorRevisaoRoute,
  GeradorIndexRoute: GeradorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
